### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mwalkerr** [naknomum/solacon#2]
Hey, this project is great! It's got the best look of the identicons that I've seen. I'd love to use it for my project but there is no license on this repo. If you'd like to allow others to use it, please select a license. As I understand, if one isn't selected, then no one has permission to use the code in the repo - https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by naknomum** [comment]
indeed!  excellent point.  especially since someone wants to use it. (thanks!)  added.
hope you can find some usefulness in it and/or have fun.   the look of the thing was actually due to a math mistake on my part.  i had intended the "petals" to be more symmetrical and teardrop-shaped and -- kinda failed.  but i like how it turned out better.

**Comment by mwalkerr** [comment]
Ha, well there's no shortage of great things that weren't what was initially intended :). Thanks for the quick response and license addition!
